spring:
  profiles:
    active: dev    
---

spring:
  profiles:
   active: dev
  application:
    name: springcloud-config-dev
---
spring:
  profiles:
   active: pro
  application:
    name: springcloud-config-pro
